version: '3'

services:
    backoffice-api:
        build: ./project/backoffice-service
        image: miguelalb/backoffice-joelcel
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
        volumes:
            - ./project/backoffice-service:/usr/src/app
        ports:
            - 8005:8001
        env_file:
            - ./project/backoffice-service/app/core/.env
        depends_on:
            - web-db
    
    # ecommerce-api:
    #     build: ./project/ecommerce-service
    #     image: miguelalb/ecommerce-joelcel
    #     command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8002
    #     volumes:
    #         - ./project/ecommerce-service:/usr/src/app
    #     ports:
    #         - 8006:8002
    #     env_file:
    #         - ./project/ecommerce-service/app/core/.env
    #     depends_on:
    #         - web-db
    
    web-db:
        build:
            context: ./project/db
            dockerfile: Dockerfile
        image: miguelalb/backendapi-db
        expose:
            - 5432
        env_file:
            - ./project/db/.env
    
    pg-admin:
        image: dpage/pgadmin4
        ports:
            - 5051:80
        env_file: 
            - ./project/db/.env
        depends_on: 
            - web-db