apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\macevedo\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backoffice-api
  name: backoffice-api
spec:
  ports:
  - name: "8005"
    port: 8005
    targetPort: 8001
  selector:
    io.kompose.service: backoffice-api
status:
  loadBalancer: {}
