apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\macevedo\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ecommerce-api
  name: ecommerce-api
spec:
  ports:
  - name: "8006"
    port: 8006
    targetPort: 8002
  selector:
    io.kompose.service: ecommerce-api
status:
  loadBalancer: {}
