apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\macevedo\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ecommerce-api
  name: ecommerce-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ecommerce-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\macevedo\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ecommerce-api
    spec:
      containers:
      - args:
        - uvicorn
        - app.main:app
        - --reload
        - --workers
        - "1"
        - --host
        - 0.0.0.0
        - --port
        - "8002"
        env:
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              key: ACCESS_TOKEN_EXPIRE_MINUTES
              name: ecommerce-api-env
        - name: BACKEND_CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              key: BACKEND_CORS_ORIGINS
              name: ecommerce-api-env
        - name: DATABASE_TEST_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_TEST_URL
              name: ecommerce-api-env
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: ecommerce-api-env
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: ENVIRONMENT
              name: ecommerce-api-env
        - name: PYTHONPATH
          valueFrom:
            configMapKeyRef:
              key: PYTHONPATH
              name: ecommerce-api-env
        - name: REFRESH_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              key: REFRESH_TOKEN_EXPIRE_MINUTES
              name: ecommerce-api-env
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: SECRET_KEY
              name: ecommerce-api-env
        - name: TESTING
          valueFrom:
            configMapKeyRef:
              key: TESTING
              name: ecommerce-api-env
        image: miguelalb/ecommerce-joelcel
        imagePullPolicy: ""
        name: ecommerce-api
        ports:
        - containerPort: 8002
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
