apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\macevedo\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ecommerce-frontend
  name: ecommerce-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ecommerce-frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\macevedo\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ecommerce-frontend
    spec:
      containers:
      - image: miguelalb/ecommerce-joelcel-frontend
        imagePullPolicy: ""
        name: frontend-ecommerce
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
