apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\macevedo\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pg-admin
  name: pg-admin
spec:
  ports:
  - name: "5051"
    port: 5051
    targetPort: 80
  selector:
    io.kompose.service: pg-admin
status:
  loadBalancer: {}
